# Load RDS data
characterInfo <- readRDS('data/rds/characterInfo.rds')
characterGender <- readRDS('data/rds/characterGender.rds')
characters <- readRDS('data/rds/characters.rds')
combiningData <- readRDS('data/rds/combiningData.rds')
episodes <- readRDS('data/rds/episodes.rds')
subtitles <- readRDS('data/rds/subtitles.rds')
seasons <- readRDS('data/rds/seasons.rds')
tidyFrasier <- readRDS('data/rds/tidyFrasier.rds')
frasierSentiment <- readRDS('data/rds/frasierSentiment.rds')