saveRDS(characterGender, file = 'data/rds/characterGender.rds')
saveRDS(characters, file = 'data/rds/characters.rds')
saveRDS(episodes, file = 'data/rds/episodes.rds')
saveRDS(subtitles, file = 'data/rds/subtitles.rds')
saveRDS(combiningData, file = 'data/rds/combiningData.rds')