# Load RDS data
characterGender <- readRDS('data/rds/characterGender.rds')
transcripts <- readRDS('data/rds/transcripts.rds')
subtitles <- readRDS('data/rds/subtitles.rds')
seasons <- readRDS('data/rds/seasons.rds')
tidyFrasier <- readRDS('data/rds/tidyFrasier.rds')
fullCastList <- readRDS('data/rds/fullCastList.rds')
frasierSentiment <- readRDS('data/rds/frasierSentiment.rds')
# mainCharacters <- readRDS('data/rds/mainCharacters.rds')
# characterInfo <- readRDS('data/rds/characterInfo.rds')
# characters <- readRDS('data/rds/characters.rds')
